# permissions for end users to edit pdfdocuments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdfdocument-editor-role
rules:
- apiGroups:
  - k8s.startkubernetes.com.k8s.startkubernetes.com
  resources:
  - pdfdocuments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.startkubernetes.com.k8s.startkubernetes.com
  resources:
  - pdfdocuments/status
  verbs:
  - get
